### PR TITLE
update Facebook API to version 2.8

### PR DESCRIPTION
**Pull request by garu**
Hi there! Once again, thank you so much for creating Net::Facebook::Oauth2. I love its simplicity and straightforwardness :)

This Pull Request is meant to update the module to the latest version of Facebook's API (2.8). This is important because **the version used in this module (2.2) is [scheduled for deletion](https://developers.facebook.com/tools/api_versioning/226201254245474/) on the 30th of october** (this month! 😱)

To help you review it, this is what the new commits do:

* update all API requests from 2.2 to 2.8;
* update optional argument list on some methods, as per 2.8 specification;
* add some missing dependencies on the Makefile.PL (they were already been used by the tests);
* update all code samples under `/examples` to the new API - removing no longer existing paths (like `/search`) and updating scopes;
* trigger a warning when someone uses this module one month prior to [API 2.8 expiration date](https://developers.facebook.com/tools/api_versioning/226201254245474/) (2018-10-05);
* update documentation to reflect said changes;
* update the README to centralize all documentation on the POD;
* bump version number to 0.10;
* bump copyright year to 2016.

It might be worth it to say that **I have tested this on live Facebook accounts** and it works perfectly. As soon as this is merged, I will issue a Pull Request on Dancer::Plugin::Auth::Facebook for the same reason (but I need this merged first since it uses this module).

Please let me know if there is anything I can do to help you merge this as soon as possible. Like I said, if we do nothing this module will stop working in a few days - and I kinda need it :D 

Thanks!

garu

### CODE REVIEW

**Comment by mamod** [comment]
@garu WOW, this is super neat man... AGAIN!!! I'll review and try to catch with what's going on here and on facebook API :)

I think I'll be merging this in less than 24 hours :+1:

**Comment by garu** [comment]
@mamod thanks! I think the link I pasted on the PR message is exclusive to my app - it's facebook's migration tool that I used to figure out what the new call parameters were :)

If it doesn't work for you, you might be able to find a similar one under "Tools & Support" -> "API Upgrade Tool" inside developer.facebook.com, but the only really important bits there are the dates where each version is scheduled for deletion.

A more important link is [this one](https://developers.facebook.com/docs/apps/versions). It explains how versions work on Facebook and it's quite terrifying, because it says *"An app can [only] make calls to the version of the API that was the latest available when the app was created, as well as any newer, un-deprecated versions launched after the app is created."* So, according to Facebook, any app created after 30 october 2014 (two years ago) could only access 2.3 and higher! All calls made by Net::Facebook::Oauth2's `2.2` endpoints were already been automatically forwarded to the newer versions for those apps 😱 

Fortunately, this module only makes `core` calls, which according to Facebook are less likely to change between versions. Still, the update is important because some changes did occur. Again, to try and help you sort them out, here's the relevant [changelog](https://developers.facebook.com/docs/apps/changelog):

#### Deprecations:

* `offline_access` scope was removed in a [deprecation in 2012](https://developers.facebook.com/docs/roadmap/completed-changes/offline-access-removal). Affected just example code and POD;
* `publish_stream` scope was [removed in favor of publish_actions](https://developers.facebook.com/blog/post/2012/04/25/streamlining-publish_stream-and-publish_actions-permissions/). Affected just example code and POD;
* `/search` endpoint to search posts was removed in version 2.1. Affected just the Catalyst example;
* the API call to fetch the access token now always returns a JSON, so we no longer have to fetch the content and split it in `&` (to fetch token and expiration) nor to split the token in `=` to separate the string from the actual token. This is perhaps the most important change, and it was made in version 2.3. The verbatim changelong for this is:

*[Oauth Access Token] Format - The response format of https://www.facebook.com/v2.3/oauth/access_token returned when you exchange a code for an access_token now return valid JSON instead of being URL encoded. The new format of this response is {"access_token": {TOKEN}, "token_type":{TYPE}, "expires_in":{TIME}}. We made this update to be compliant with section 5.1 of RFC 6749.*

#### [Additions to the login arguments](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#login):

* `state` argument (optional) added to authorization URL to help protect against CSRF;
* `response_type` argument (optional) added to authorization URL to control how response data is returned;
* `auth_type` argument (optional) added to authorization URL to [re-ask for declined permissions](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#reaskperms) (which do not show up on the login dialog anymore, so we must pass this argument explicitly);

#### Other modifications:

* Facebook is not explicit in the docs on what the HTTP status code will be in case of errors, but it does say that in case of errors the API will return a JSON explaining what it is, so I changed the error checking from `! $response->is_success` to `! $response->is_success || exists $json->{error}`;

Thank you so much for your quick response to the PR! I hope this helps :D

**Comment by mamod** [comment]
Sorry for the delay an unexpected event blocked me from fulfilling my 24 hours promise :disappointed:

Had the chance to test with my API test account but you saved me going through the whole API documentation with this great highlight :smile: this is what I call a perfect pull request, CPAN release on it's way.

Thank you man your awesome.

**Comment by garu** [comment]
No no... thank you for doing this so quickly! Just saw the new release on CPAN - I really appreciate it :) 

(speaking of which, metacpan spotted a pod error which I fixed on #13 - hope it helps!)

Cheers! And thanks again!

**Pull request merged**
